//
// Copyright 2016 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-android v0.13
//
package com.amazonaws.mobile;

import com.amazonaws.regions.Regions;

/**
 * This class defines constants for the developer's resource
 * identifiers and API keys. This configuration should not
 * be shared or posted to any public source code repository.
 */
public class AWSConfiguration {
    // AWS MobileHub user agent string
    public static final String AWS_MOBILEHUB_USER_AGENT =
        "MobileHub 3912f550-b3ff-4de7-8c79-3a324fc81b51 aws-my-sample-app-android-v0.13";
    // AMAZON COGNITO
    public static final Regions AMAZON_COGNITO_REGION =
      Regions.fromName("us-east-1");
    public static final String  AMAZON_COGNITO_IDENTITY_POOL_ID =
        "us-east-1:c1c2ff8f-5a35-4cd5-b281-7843dd9ee91f";
    public static final String AMAZON_COGNITO_USER_POOL_ID =
        "us-east-1_P4Df29JFZ";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_ID =
        "75b5d3l4k0rhk32u581ngf78a5";
    public static final String AMAZON_COGNITO_USER_POOL_CLIENT_SECRET =
        "7pbn1itsels808bbi9vim5h30a3rsn46qg8ma9b5n4a116a11ph";
}
